//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.23 at 10:28:01 AM CET 
//


package com.dsi301.xml.shipment;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dsi301.xml.shipment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dsi301.xml.shipment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentRequest }
     * 
     */
    public ShipmentRequest createShipmentRequest() {
        return new ShipmentRequest();
    }

    /**
     * Create an instance of {@link ShipmentDetailsRequest }
     * 
     */
    public ShipmentDetailsRequest createShipmentDetailsRequest() {
        return new ShipmentDetailsRequest();
    }

    /**
     * Create an instance of {@link ShipmentDetailsResponse }
     * 
     */
    public ShipmentDetailsResponse createShipmentDetailsResponse() {
        return new ShipmentDetailsResponse();
    }

    /**
     * Create an instance of {@link ShipmentResponse }
     * 
     */
    public ShipmentResponse createShipmentResponse() {
        return new ShipmentResponse();
    }

}
