//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.23 at 10:28:01 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.dsi301.com/xml/shipment", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dsi301.xml.shipment;
